//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_SKELETALANIMATIONSCENE_H
#define LEARNGLES_SKELETALANIMATIONSCENE_H


class SkeletalAnimationScene {

};


#endif //LEARNGLES_SKELETALANIMATIONSCENE_H
