//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_BASICLIGHTINGDIFFUSESCENE_H
#define LEARNGLES_BASICLIGHTINGDIFFUSESCENE_H


class BasicLightingDiffuseScene {

};


#endif //LEARNGLES_BASICLIGHTINGDIFFUSESCENE_H
