//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_LIGHTINGCASTERSSPOTSOFTSCENE_H
#define LEARNGLES_LIGHTINGCASTERSSPOTSOFTSCENE_H


class LightingCastersSpotSoftScene {

};


#endif //LEARNGLES_LIGHTINGCASTERSSPOTSOFTSCENE_H
