//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_LIGHTINGMAPSDIFFUSEMAPSCENE_H
#define LEARNGLES_LIGHTINGMAPSDIFFUSEMAPSCENE_H


class LightingMapsDiffuseMapScene {

};


#endif //LEARNGLES_LIGHTINGMAPSDIFFUSEMAPSCENE_H
