//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_LIGHTINGCASTERSDIRECTIONALSCENE_H
#define LEARNGLES_LIGHTINGCASTERSDIRECTIONALSCENE_H


class LightingCastersDirectionalScene {

};


#endif //LEARNGLES_LIGHTINGCASTERSDIRECTIONALSCENE_H
