//
// Created by zoozo on 8/9/2023.
//

#ifndef LEARNGLES_COORDINATESYSTEMEXERCISE3SCENE_H
#define LEARNGLES_COORDINATESYSTEMEXERCISE3SCENE_H


class CoordinateSystemExercise3Scene {

};


#endif //LEARNGLES_COORDINATESYSTEMEXERCISE3SCENE_H
