//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_CUBEMAPSENVIRONMENTMAPPINGSCENE_H
#define LEARNGLES_CUBEMAPSENVIRONMENTMAPPINGSCENE_H


class CubemapsEnvironmentMappingScene {

};


#endif //LEARNGLES_CUBEMAPSENVIRONMENTMAPPINGSCENE_H
