//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_GEOMETRYSHADERHOUSESSCENE_H
#define LEARNGLES_GEOMETRYSHADERHOUSESSCENE_H


class GeometryShaderHousesScene {

};


#endif //LEARNGLES_GEOMETRYSHADERHOUSESSCENE_H
