//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_IBLSPECULARTEXTUREDSCENE_H
#define LEARNGLES_IBLSPECULARTEXTUREDSCENE_H


class IblSpecularTexturedScene {

};


#endif //LEARNGLES_IBLSPECULARTEXTUREDSCENE_H
