//
// Created by huion on 2023/8/22.
//

#ifndef LEARNGLES_SHADOWMAPPINGBASESCENE_H
#define LEARNGLES_SHADOWMAPPINGBASESCENE_H


class ShadowMappingBaseScene {

};


#endif //LEARNGLES_SHADOWMAPPINGBASESCENE_H
